In [2]:
import numpy as np
import pandas as pd
import os

In [7]:
print(os.getcwd())
os.chdir("E:\python\project\python\随堂\pandas")
student=pd.read_csv("./data/students.csv")
student

E:\python\project\python\随堂\pandas

  name   age
0   张三  15.0
1   李四  20.0
2   王五   NaN
3   赵六  15.0

In [11]:
# 用0填充
s1=student.fillna(0)
print(s1)

  name   age
0   张三  15.0
1   李四  20.0
2   王五   0.0
3   赵六  15.0

In [13]:
# 平均值填充
s2=student.fillna(student["age"].mean())
s2

  name        age
0   张三  15.000000
1   李四  20.000000
2   王五  16.666667
3   赵六  15.000000

In [15]:
# 使用后面不为none的值填充
s3=student.bfill()
s3

  name   age
0   张三  15.0
1   李四  20.0
2   王五  15.0
3   赵六  15.0

In [17]:
# 使用前值填充
s4=student.ffill()
s4

  name   age
0   张三  15.0
1   李四  20.0
2   王五  20.0
3   赵六  15.0