In [20]:
import numpy as np
import pandas as pd
import os

In [33]:
print(os.getcwd())
df=pd.read_csv('./data/survey_visited.csv')
df

E:\python\project\python\pandas

    ident   site       dated
0   619.0   DR-1  1927-02-08
1   622.0   DR-1  1927-02-10
2   734.0   DR-3  1939-01-07
3   735.0   DR-3  1930-01-12
4   751.0   DR-3  1930-02-26
5   752.0   DR-3         NaN
6   837.0  MSK-4  1932-01-14
7   844.0   DR-1  1932-03-22
8   666.0    NaN         NaN
9   888.0    NaN         NaN
10  999.0    NaN         NaN
11    NaN    NaN         NaN
12    NaN    NaN         NaN

In [28]:
df=pd.read_csv('./data/survey_visited.csv',keep_default_na=False,na_values=["",None,pd.NA,np.nan])
df.head(15)

    ident   site       dated
0   619.0   DR-1  1927-02-08
1   622.0   DR-1  1927-02-10
2   734.0   DR-3  1939-01-07
3   735.0   DR-3  1930-01-12
4   751.0   DR-3  1930-02-26
5   752.0   DR-3         NaN
6   837.0  MSK-4  1932-01-14
7   844.0   DR-1  1932-03-22
8   666.0   NULL        null
9   888.0    NaN          NA
10  999.0    NaN         NaN
11    NaN    NaN         NaN
12    NaN    NaN         NaN

In [41]:

os.chdir("E:\python\project\python\随堂\pandas")
ds=pd.read_csv('data/titanic_train.csv')
# 统计列空值数据
ds.isna().sum() 
ds["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
887    19.0
888     NaN
889    26.0
890    32.0
891     NaN
Name: Age, Length: 892, dtype: float64