# dataFrame 常用属性及方法

## 1 常用属性

In [58]:
# 导包
import pandas as pd
import numpy as np

In [59]:
arr=np.random.randint(40,100,size=(10,5),dtype=np.int32)
df=pd.DataFrame(arr,columns=["语文","数学","英语","生物","化学"],index=["同学"+ str(i) for i in range(10)])
df

     语文  数学  英语  生物  化学
同学0  51  90  74  51  75
同学1  76  48  82  82  86
同学2  50  76  88  53  64
同学3  91  87  98  91  74
同学4  48  66  56  92  44
同学5  78  42  74  62  98
同学6  56  81  86  93  69
同学7  87  88  82  56  47
同学8  70  83  43  54  54
同学9  50  99  61  82  98

In [60]:
# 常见属性
# 属性1: index 获取数据的行索引
df.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [61]:
# 属性2: columns 获取数据的列名
df.columns

Index(['语文', '数学', '英语', '生物', '化学'], dtype='object')

In [62]:
# 属性3: values 获取数据的所有值
df.values

array([[51, 90, 74, 51, 75],
       [76, 48, 82, 82, 86],
       [50, 76, 88, 53, 64],
       [91, 87, 98, 91, 74],
       [48, 66, 56, 92, 44],
       [78, 42, 74, 62, 98],
       [56, 81, 86, 93, 69],
       [87, 88, 82, 56, 47],
       [70, 83, 43, 54, 54],
       [50, 99, 61, 82, 98]], dtype=int32)

In [63]:
# 属性4 size 获取数据的长度
df.size

50

In [64]:
# 属性5 dtypes 数据元素的类型(取决于定义时的数据类型,此处由numpy定义)
df.dtypes

语文    int32
数学    int32
英语    int32
生物    int32
化学    int32
dtype: object

In [65]:
# 属性6 T 数据转置 (将数据的行和列互换,数据也随之互换)
df.T

    同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   51   76   50   91   48   78   56   87   70   50
数学   90   48   76   87   66   42   81   88   83   99
英语   74   82   88   98   56   74   86   82   43   61
生物   51   82   53   91   92   62   93   56   54   82
化学   75   86   64   74   44   98   69   47   54   98

## 2 常用方法

In [66]:
# 方法1 head() 查看数据前()行数据,默认5行
df.head()

     语文  数学  英语  生物  化学
同学0  51  90  74  51  75
同学1  76  48  82  82  86
同学2  50  76  88  53  64
同学3  91  87  98  91  74
同学4  48  66  56  92  44

In [67]:

# 方法2 tail() 查看数据后()行数据,默认5行
df.tail(10)

     语文  数学  英语  生物  化学
同学0  51  90  74  51  75
同学1  76  48  82  82  86
同学2  50  76  88  53  64
同学3  91  87  98  91  74
同学4  48  66  56  92  44
同学5  78  42  74  62  98
同学6  56  81  86  93  69
同学7  87  88  82  56  47
同学8  70  83  43  54  54
同学9  50  99  61  82  98

In [68]:
# 方法3 describe() 获取数据描述信息
df.describe()

              语文         数学         英语         生物         化学
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   65.700000  76.000000  74.400000  71.600000  70.900000
std    16.620269  18.571184  16.654662  17.895996  19.307166
min    48.000000  42.000000  43.000000  51.000000  44.000000
25%    50.250000  68.500000  64.250000  54.500000  56.500000
50%    63.000000  82.000000  78.000000  72.000000  71.500000
75%    77.500000  87.750000  85.000000  88.750000  83.250000
max    91.000000  99.000000  98.000000  93.000000  98.000000

In [69]:
# 方法4 info() 获取数据详细信息
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 同学0 to 同学9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int32
 1   数学      10 non-null     int32
 2   英语      10 non-null     int32
 3   生物      10 non-null     int32
 4   化学      10 non-null     int32
dtypes: int32(5)
memory usage: 580.0+ bytes

In [70]:
## 3 修改索引
new_columns=["python基础","python进阶","数据分析","深度学习","神经网络"]
new_index=["stu_"+str(i) for i in range(10)]
df.index=new_index
df.columns=new_columns
df

       python基础  python进阶  数据分析  深度学习  神经网络
stu_0        51        90    74    51    75
stu_1        76        48    82    82    86
stu_2        50        76    88    53    64
stu_3        91        87    98    91    74
stu_4        48        66    56    92    44
stu_5        78        42    74    62    98
stu_6        56        81    86    93    69
stu_7        87        88    82    56    47
stu_8        70        83    43    54    54
stu_9        50        99    61    82    98

## 3 修改索引

In [71]:
idx_df=pd.DataFrame({
    "month":[1,3,6,34],
    "sale":[23,54,32,16],
    "year":[2010,2011,2012,2013]
})
idx_df

   month  sale  year
0      1    23  2010
1      3    54  2011
2      6    32  2012
3     34    16  2013

In [72]:
# 设置month为索引列
#idx_df.set_index("month",inplace=True)
# idx_df.drop()
#取消设置索引列
# idx_df.reset_index(inplace=True)
idx_df

   month  sale  year
0      1    23  2010
1      3    54  2011
2      6    32  2012
3     34    16  2013

In [75]:
# 设置多行索引列
#idx_df.set_index(["month","year"],inplace=True)
idx_df

            sale
month year
1     2010    23
3     2011    54
6     2012    32
34    2013    16

## 4 DataFrame 的数据类型

In [78]:
#datetime 时间日期类型
date=pd.to_datetime("2018-01-01")
date

Timestamp('2018-01-01 00:00:00')

In [81]:
# timedelta 时间差类型
start_time=pd.to_datetime("2018-01-10")
end_time=pd.to_datetime("2018-01-20")
print(end_time-start_time)
print(type(end_time-start_time))

10 days 00:00:00
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>

In [82]:
# category 类型 ,只保存索引和唯一值
fruit=pd.Series(["apple","banana","cherry","apple","banana","peach","orange"],dtype="category")
print(fruit)
print(type(fruit))

0     apple
1    banana
2    cherry
3     apple
4    banana
5     peach
6    orange
dtype: category
Categories (5, object): ['apple', 'banana', 'cherry', 'orange', 'peach']
<class 'pandas.core.series.Series'>