# DataFrane 获取数据

In [2]:
# 导包
import pandas as pd
import os

In [11]:
# 修改工作路径
os.chdir("/Users/baidengchao/Desktop/code/python/pandas")
crd=os.getcwd()
crd

'/Users/baidengchao/Desktop/code/python/pandas'

In [14]:
 ## 1 读取数据
ds=pd.read_csv('./data/stock_day.csv')
ds.head(10)

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
2018-02-13,21.40,21.90,21.48,21.31,30802.45,0.28,1.32,21.342,22.103,23.387,39694.65,45518.14,65161.68,0.77
2018-02-12,20.70,21.40,21.19,20.63,32445.39,0.82,4.03,21.504,22.338,23.533,44645.16,45679.94,68686.33,0.81
2018-02-09,21.20,21.46,20.36,20.19,54304.01,-1.50,-6.86,21.920,22.596,23.645,48624.36,48982.38,70552.47,1.36
2018-02-08,21.79,22.09,21.88,21.75,27068.16,0.09,0.41,22.372,23.009,23.839,44411.98,48612.16,73852.45,0.68
2018-02-07,22.69,23.11,21.80,21.29,53853.25,-0.50,-2.24,22.480,23.258,23.929,52281.28,56315.11,74925.33,1.35

## 1 获取数据

In [18]:
# 根据索引获取具体数据(例如:第一行第一列) [先列后行]
value=ds["open"]["2018-02-27"]
value1=ds["close"]["2018-02-27"]
value1

np.float64(24.16)

In [22]:
#通过loc属性来获取，只能通过：行索引+列名的方式来获取
value2=ds.loc["2018-02-27","open"]
value3=ds.loc["2018-02-27"]["close"]
print(value3)

24.16

In [31]:
# 需求：获取从2018-02-27 - 2018-02-22的open列数据
targetList=ds.loc["2018-02-27":"2018-02-22"]
# print(targetList)
# 需求：获取从2018-02-27 - 2018-02-22的open, high, close, low列数据
table=ds.loc["2018-02-27":"2018-02-22",["open","close","high","low"]]
# 需求：获取从2018-02-27 - 2018-02-22的所有列数据
list1=ds.loc["2018-02-27":"2018-02-22"]
list2=ds.loc["2018-02-27":"2018-02-22",:]
# list2

In [41]:
#根据行号和列号获取数据
# 格式 先行后列,行和列的编号  数据源[行号,列号]
list4=ds.iloc[0,1]
# 根据行号和列号获取范围(区间)数据 
# 获取0到5行的所有列
list5=ds.iloc[0:5,:]
# 获取0到5行的0到6列数据
list6=ds.iloc[0:5,0:6]
# list6


## 2 添加和删除列

In [49]:
# 添加新列
# 添加列 数据源[列名] 如果列名存在则为修改值,如果不存在则添加新列
# ds["diff_close"]=ds["close"]-ds["open"]
# 删除列
"""
    格式: 数据源drop([列名],axis=1,inplace=True) 
    参数说明: 
        1、删除一列直接写列名即可,多列用[]包裹,
        2、axis 1代表列,0代表行
        3、inplace: 布尔值,是否修改源数据
"""
# ds.drop(["ma5","ma10","ma20","v_ma5","v_ma10","v_ma20"],axis=1,inplace=True)
ds

,open,high,close,low,volume,price_change,p_change,turnover,diff_close
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39,0.63
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53,0.73
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32,-0.06
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90,0.03
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58,0.43
...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16,1.11
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19,0.28
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30,0.10
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76,0.18
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30,0.27

## 3 DataFrame和Series的排序操作

In [50]:
ds

,open,high,close,low,volume,price_change,p_change,turnover,diff_close
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39,0.63
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53,0.73
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32,-0.06
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90,0.03
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58,0.43
...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16,1.11
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19,0.28
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30,0.10
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76,0.18
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30,0.27