# DataFrame新增列

In [22]:
# 1导包
import pandas as pd
import os
os.chdir("E:\python\project\python\pandas")

ds=pd.read_csv('./data/1960-2019全球GDP数据.csv',encoding="gbk").head()
ds

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [ ]:
# 添加新列=====> 格式: 数据源[列名]=值   **该操作会修改源数据**
ds["col1"]=22
ds["col2"]=[1,2,3,4,5]
ds["col3"]=ds.index*3

In [24]:
# 添加新列 assign方法======> 数据源.assign()  **当前操作不会修改源数据**
ds.assign(col1=11) # 直接传入数值
ds.assign(col2=[1,2,3,4,5]) # 直接写数据
def getNewCOl(ds): 
    return  ds.year*2
ds.assign(col3=getNewCOl) # 使用自定义函数
s=pd.Series(["乔峰","段誉","虚竹","天山童姥"]) # 使用Series新增,缺少的行不会报错,但是会用NaN补齐
ds.assign(col4=s)

   year country           GDP  col4
0  1960      美国  543300000000    乔峰
1  1960      英国   73233967692    段誉
2  1960      法国   62225478000    虚竹
3  1960      中国   59716467625  天山童姥
4  1960      日本   44307342950   NaN