# dataFrame 常用属性及方法

## 1 常用属性

In [39]:
# 导包
import pandas as pd
import numpy as np

In [40]:
arr=np.random.randint(40,100,size=(10,5),dtype=np.int32)
df=pd.DataFrame(arr,columns=["语文","数学","英语","生物","化学"],index=["同学"+ str(i) for i in range(10)])
df

     语文  数学  英语  生物  化学
同学0  82  88  42  50  88
同学1  85  97  68  95  93
同学2  81  68  61  42  64
同学3  55  65  52  59  59
同学4  49  66  78  56  48
同学5  81  80  89  53  89
同学6  72  56  93  91  68
同学7  79  43  85  55  53
同学8  70  56  76  88  86
同学9  48  88  83  52  55

In [41]:
# 常见属性
# 属性1: index 获取数据的行索引
df.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [42]:
# 属性2: columns 获取数据的列名
df.columns

Index(['语文', '数学', '英语', '生物', '化学'], dtype='object')

In [43]:
# 属性3: values 获取数据的所有值
df.values

array([[82, 88, 42, 50, 88],
       [85, 97, 68, 95, 93],
       [81, 68, 61, 42, 64],
       [55, 65, 52, 59, 59],
       [49, 66, 78, 56, 48],
       [81, 80, 89, 53, 89],
       [72, 56, 93, 91, 68],
       [79, 43, 85, 55, 53],
       [70, 56, 76, 88, 86],
       [48, 88, 83, 52, 55]], dtype=int32)

In [44]:
# 属性4 size 获取数据的长度
df.size

50

In [45]:
# 属性5 dtypes 数据元素的类型(取决于定义时的数据类型,此处由numpy定义)
df.dtypes

语文    int32
数学    int32
英语    int32
生物    int32
化学    int32
dtype: object

In [46]:
# 属性6 T 数据转置 (将数据的行和列互换,数据也随之互换)
df.T

    同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   82   85   81   55   49   81   72   79   70   48
数学   88   97   68   65   66   80   56   43   56   88
英语   42   68   61   52   78   89   93   85   76   83
生物   50   95   42   59   56   53   91   55   88   52
化学   88   93   64   59   48   89   68   53   86   55

## 2 常用方法

In [47]:
# 方法1 head() 查看数据前()行数据,默认5行
df.head()

     语文  数学  英语  生物  化学
同学0  82  88  42  50  88
同学1  85  97  68  95  93
同学2  81  68  61  42  64
同学3  55  65  52  59  59
同学4  49  66  78  56  48

In [48]:

# 方法2 tail() 查看数据后()行数据,默认5行
df.tail(10)

     语文  数学  英语  生物  化学
同学0  82  88  42  50  88
同学1  85  97  68  95  93
同学2  81  68  61  42  64
同学3  55  65  52  59  59
同学4  49  66  78  56  48
同学5  81  80  89  53  89
同学6  72  56  93  91  68
同学7  79  43  85  55  53
同学8  70  56  76  88  86
同学9  48  88  83  52  55

In [49]:
# 方法3 describe() 获取数据描述信息
df.describe()

              语文         数学         英语         生物         化学
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   70.200000  70.700000  72.700000  64.100000  70.300000
std    14.320149  17.120813  16.680328  19.381836  17.088333
min    48.000000  43.000000  42.000000  42.000000  48.000000
25%    58.750000  58.250000  62.750000  52.250000  56.000000
50%    75.500000  67.000000  77.000000  55.500000  66.000000
75%    81.000000  86.000000  84.500000  80.750000  87.500000
max    85.000000  97.000000  93.000000  95.000000  93.000000

In [50]:
# 方法4 info() 获取数据详细信息
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 同学0 to 同学9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int32
 1   数学      10 non-null     int32
 2   英语      10 non-null     int32
 3   生物      10 non-null     int32
 4   化学      10 non-null     int32
dtypes: int32(5)
memory usage: 580.0+ bytes

In [51]:
## 3 修改索引
new_columns=["python基础","python进阶","数据分析","深度学习","神经网络"]
new_index=["stu_"+str(i) for i in range(10)]
df.index=new_index
df.columns=new_columns
df

       python基础  python进阶  数据分析  深度学习  神经网络
stu_0        82        88    42    50    88
stu_1        85        97    68    95    93
stu_2        81        68    61    42    64
stu_3        55        65    52    59    59
stu_4        49        66    78    56    48
stu_5        81        80    89    53    89
stu_6        72        56    93    91    68
stu_7        79        43    85    55    53
stu_8        70        56    76    88    86
stu_9        48        88    83    52    55

## 3 修改索引

In [52]:
idx_df=pd.DataFrame({
    "month":[1,3,6,34],
    "sale":[23,54,32,16],
    "year":[2010,2011,2012,2013]
})
idx_df

   month  sale  year
0      1    23  2010
1      3    54  2011
2      6    32  2012
3     34    16  2013

In [56]:
# 设置month为索引列
#idx_df.set_index("month",inplace=True)
# idx_df.drop()
#取消设置索引列
# idx_df.reset_index(inplace=True)
idx_df

   year  month  sale
0  2010      1    23
1  2011      3    54
2  2012      6    32
3  2013     34    16

In [57]:
# 设置多行索引列
idx_df.set_index(["month","year"],inplace=True)
idx_df

            sale
month year
1     2010    23
3     2011    54
6     2012    32
34    2013    16