# DataFrame新增列

In [2]:
# 1导包
import pandas as pd
import os
os.chdir("E:\python\project\python\pandas")

ds=pd.read_csv('./data/1960-2019全球GDP数据.csv',encoding="gbk").head()
ds

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [3]:
# 添加新列=====> 格式: 数据源[列名]=值   **该操作会修改源数据**
ds["col1"]=22
ds["col2"]=[1,2,3,4,5]
ds["col3"]=ds.index*3

In [5]:
# 添加新列 assign方法======> 数据源.assign()  **当前操作不会修改源数据**
ds.assign(col1=11) # 直接传入数值
ds.assign(col2=[1,2,3,4,5]) # 直接写数据
def getNewCOl(ds): 
    return  ds.year*2
ds.assign(col3=getNewCOl) # 使用自定义函数
s=pd.Series(["乔峰","段誉","虚竹","天山童姥"]) # 使用Series新增,缺少的行不会报错,但是会用NaN补齐
ds.assign(col4=s)

   year country           GDP  col1  col2  col3  col4
0  1960      美国  543300000000    22     1     0    乔峰
1  1960      英国   73233967692    22     2     3    段誉
2  1960      法国   62225478000    22     3     6    虚竹
3  1960      中国   59716467625    22     4     9  天山童姥
4  1960      日本   44307342950    22     5    12   NaN

# 删除列

In [19]:
ds
# ds.drop("col3",axis=1,inplace=True) # 删除列,axis=1-------> 1: 列,0:行

   year country           GDP  col1  col2
0  1960      美国  543300000000    22     1
1  1960      英国   73233967692    22     2
2  1960      法国   62225478000    22     3
3  1960      中国   59716467625    22     4
4  1960      日本   44307342950    22     5

In [50]:
# 删除多列
ds.drop(["col1","col2"],axis=1)
ds

   year country           GDP  col1  col2
0  1960      美国  543300000000    22     1
1  1960      英国   73233967692    22     2
2  1960      法国   62225478000    22     3
3  1960      中国   59716467625    22     4
4  1960      日本   44307342950    22     5

In [57]:
#drop_duplicates 和unique 去重都适用于Series对象,
ds1=ds.copy()
# ds1.year.drop_duplicates()
ds1["col1"].unique()
ds1

   year country           GDP  col1  col2
0  1960      美国  543300000000    22     1
1  1960      英国   73233967692    22     2
2  1960      法国   62225478000    22     3
3  1960      中国   59716467625    22     4
4  1960      日本   44307342950    22     5

# 修改列

In [117]:
df=pd.read_csv('./data/1960-2019全球GDP数据.csv',encoding="gbk")
df1=df
df1=df1.assign(col1=21)
# df1.col1=33
df1.assign(col1=99)
# df1.drop("col1", axis=1,inplace=True)

      year   country           GDP  col1
0     1960        美国  543300000000    99
1     1960        英国   73233967692    99
2     1960        法国   62225478000    99
3     1960        中国   59716467625    99
4     1960        日本   44307342950    99
...    ...       ...           ...   ...
9925  2019  圣多美和普林西比     418637388    99
9926  2019        帕劳     268354919    99
9927  2019      基里巴斯     194647201    99
9928  2019        瑙鲁     118223430    99
9929  2019       图瓦卢      47271463    99

[9930 rows x 4 columns]

In [104]:
# 使用replace替换修改
df2=df1.copy()
# df2.col1.replace(21,56,inplace=True)
print(type(df2["year"]))
# df2["year"].replace(1960,2025,inplace=True)

df2

<class 'pandas.core.series.Series'>

   year country           GDP  col1
0  2025      美国  543300000000    56
1  2025      英国   73233967692    56
2  2025      法国   62225478000    56
3  2025      中国   59716467625    56
4  2025      日本   44307342950    56

In [112]:
# 6. query()函数, 查看数据.
# 需求1: 查看中国的数据集. 
df2[df2.country=="中国"]
df2.query("country=='中国'")

   year country          GDP  col1
3  2025      中国  59716467625    56

In [128]:
# 需求2: 查看中美日三国, 2015 ~ 2019年的数据. 
df1.query("country in ['中国','美国','日本'] & year in [2015,2016,2017,2018,2019]" )
df1.query("country in ['中国','美国','日本'] and year in [2015,2016,2017,2018,2019]" )
df1.query("country in ['中国','美国','日本']").query( "year in [2015,2016,2017,2018,2019]")

      year country             GDP  col1
8928  2015      美国  18224700000000    21
8929  2015      中国  11061600000000    21
8930  2015      日本   4389480000000    21
9133  2016      美国  18715000000000    21
9134  2016      中国  11233300000000    21
9135  2016      日本   4922540000000    21
9338  2017      美国  19519400000000    21
9339  2017      中国  12310400000000    21
9340  2017      日本   4866860000000    21
9542  2018      美国  20580200000000    21
9543  2018      中国  13894800000000    21
9544  2018      日本   4954810000000    21
9745  2019      美国  21433200000000    21
9746  2019      中国  14279900000000    21
9747  2019      日本   5081770000000    21